### PR TITLE
Dm usage

### PR DESCRIPTION
**Pull request by djbard**
I've added a recipe for using DM to detect and measure objects in a phosim image. It's pretty basic, but before I go much further with DM examples I wonder if "ImageSimulationRecipes" is the correct place for it to live. We're analysing an ImSIm image so in principal it fits with the aim of this package, but we could just as easily start a DMRecipes repository and put it there. 
 I'm in favour of having one recipe repository, and doing a bit of re-organisation in the naming, i.e. DESCRecipes/ImageSimulation and DESCRecipes/DMImageAnalysis or similar. 
Thoughts?

### CODE REVIEW

**Comment by jchiang87** [comment]
You might also want to have a look at RHL's processFile package, in particular,

https://dev.lsstcorp.org/cgit/contrib/processFile.git/tree/bin/processFile.py

Robert mentioned this in the Data Management room on hipchat yesterday shortly after Jim Bosch showed a similar ipython notebook at the SAWG meeting.  Robert mentioned on hipchat that he was hoping processFile.py would provide a way of doing image analysis with the DM stack that was as easy to use as SExtractor.  _My_ hope is that processFile makes its way to github somewhere.

**Comment by djbard** [comment]
and my hope would be that it gets documented somewhere! As-is, I suppose the idea would be that you can just run processFile over your image and tell it what to give you back, a la SExtractor.

**Comment by drphilmarshall** [comment]
I'd be in favor of merging this, and then immediately renaming this repo "Recipes". The DESC is in the organization name, and hopefully in everyone's directory superstructure... And then the web address would be darkenergysciencecollaboration.github.io/Recipes, which is nice. I think we talked about doing this ages ago, just never got round to implementing it. Once we have gone general, we can start checking in other kinds of recipes besides - a Recipe for getting set up as a SLAC user, for example.

**Comment by wmwv** [comment]
I use processFile.py on my WIYN images successfully.  Here's a sample PBS script to run on NERSC Carver:

#PBS -q serial
#PBS -l pvmem=4GB
#PBS -l walltime=01:30:00 
#PBS -N iPTF13dge_test3
#PBS -j oe  

#!/bin/sh

# python wiynAssembleExp.py 

module swap pgi gcc

# Set up LSST environment
. ~/.bashrc.lsst
setup lsst
setup -j -r ${HOME}/lsst/obs_file

WORKDIR=${PBS_O_HOME}/workspace
cd $WORKDIR

# Overwrite the catalog location to get the 2MASS catalogs.
export ASTROMETRY_NET_DATA_DIR=/project/projectdirs/m1727/cat/2MASS

RELEASEBASE=/global/scratch2/sd/wmwv/WIYN/mwv

snname="iPTF13dge"

for imfile in `ls $RELEASEBASE/${snname}_?_*_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].fits`; do
    python wiynAssembleExp.py $imfile
    basefile=${imfile%%.fits}
    lsstimname=${basefile}.lsst.fits

    outdir=$WORKDIR/$snname/`basename $basefile`

    processFile.py ${lsstimname} \
      --output $outdir \
      --clobber-output --clobber-config \
      -c gain=3.4 \
      --config calibrate.initialPsf.fwhm=1.1 \
               calibrate.astrometry.solver.calculateSip=False \
               isBackgroundSubtracted=True 

done

**Comment by djbard** [comment]
@wmwv let's adapt this into a recipe :) 
@drphilmarshall unless there's any violent opposition to this, I'll merge/rename later this week.

**Pull request merged**
